<?php
/**
 * @category    MageHack
 * @package     MageHack_MageConsole
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <div id="terminal"></div>
    <script type="text/javascript">
    jQuery(function($, undefined) {
        $('#terminal').terminal(function(command, term) {
            if (command !== '') {
                try {
                    var result = window.eval(command);
                    if (result !== undefined) {
                        term.echo(new String(result));
                    }
                } catch(e) {
                    term.error(new String(e));
                }
            } else {
               term.echo('');
            }
        }, {
            greetings: 'Magento Console',
            name: 'mageconsole',
            height: 200,
            prompt: 'Mage> '});
    });
    </script>
